### PR TITLE
Changed the gts graphing object’s default values

### PR DESCRIPTION
**Pull request by Yuming-Zhang**
Changed the gts graphing object’s default values for : axis.x.label, axis.y.label to 'Time' and 'Observation'

### CODE REVIEW

**Comment by coatless** [comment]
Welcome to GitHub @Yuming-Zhang !

Few notes:

1. The derivatives of the equation should also update after you change them (e.g. QN to WV had its coefficients switch from 3/2 and to 6. This should trickle down to the first derivative, etc. )

With this being said, please update:
* RW to Haar WV also needs to be updated to: 
     * \[{\nu ^2}\left( \tau  \right) = \frac{{{\sigma ^2}\left( {2{\tau ^2} + 4} \right)}}{{24\tau }}\]
* Please add the MA(1) process given as:
     * \[{\nu ^2}\left( { \tau } \right) = \left( {1 + {\theta ^2}} \right)\frac{{\left[ {\frac{\tau }{2} - \left( {\tau  - 3} \right)\left( {\frac{\theta }{{1 + {\theta ^2}}}} \right)} \right]}}{{\frac{{{\tau ^2}}}{4}}}{\sigma ^2}\]
     * Please derive the first and second derivatives with respect to both theta and sigma^2 (use mathematica, matlab, or maple)

* Please update the AR(1) process to use:
     * \[{\nu ^2}\left( { \tau } \right) = \frac{{\left( {\frac{\tau }{2} - 3\phi  - \frac{{\tau {\phi ^2}}}{2} + 4{\phi ^{\frac{\tau }{2} + 1}} - {\phi ^{\tau  + 1}}} \right){\sigma ^2}}}{{\frac{{{\tau ^2}}}{2}{{\left( {1 - \phi } \right)}^2}\left( {1 - {\phi ^2}} \right)}}\]
     *  (Also redo the derivative with the coefficient change)

* Please update DR as well:
     * \[{\nu ^2}\left( \tau  \right) = \frac{{{\tau ^2}{\omega ^2}}}{{16}}\]

* Note: The above were all correctly implemented. The accompanying documentation never was "updated" to use the correct WV limits described in "Allan variance of time series models for measurement data" and "Study of Allan Variance-based Techniques for Time Series Model Estimation and Wavelet Variance-based Improvements"

2. Please also commit the WV vignette. 

Place the WV vignette in the /vignettes folder. Make sure to change the vignette header information as well!

**Comment by coatless** [comment]
@Yuming-Zhang 

Will this be ready for Friday?

**Comment by coatless** [comment]
@Yuming-Zhang 

Please make comments regarding code issues here instead of in the commit. 

e.g. commits should provide a summary of what is contained. 

Issues should be mentioned here. 

Also, please comment that the submission has been updated so I am paged immediately.

Since there are three symbols in play here, matlab needs to have the following declaration:

syms tau phi sigma

f=((tau/2-3*phi-(tau*phi^2/2)+4*phi^(tau/2+1)-phi^(tau+1))*sigma^2)/(tau^2/2*(1-phi)^2*(1-phi^2))

diff(f,phi,2)

This yields:

(12*sigma^2*(3*phi - tau/2 - 4*phi^(tau/2 + 1) + (phi^2*tau)/2 + phi^(tau + 1)))/(tau^2*(phi^2 - 1)*(phi - 1)^4) - (4*sigma^2*(3*phi - tau/2 - 4*phi^(tau/2 + 1) + (phi^2*tau)/2 + phi^(tau + 1)))/(tau^2*(phi^2 - 1)^2*(phi - 1)^2) - (8*sigma^2*(phi*tau - 4*phi^(tau/2)*(tau/2 + 1) + phi^tau*(tau + 1) + 3))/(tau^2*(phi^2 - 1)*(phi - 1)^3) + (2*sigma^2*(tau - 2*phi^(tau/2 - 1)*tau*(tau/2 + 1) + phi^(tau - 1)*tau*(tau + 1)))/(tau^2*(phi^2 - 1)*(phi - 1)^2) + (16*phi^2*sigma^2*(3*phi - tau/2 - 4*phi^(tau/2 + 1) + (phi^2*tau)/2 + phi^(tau + 1)))/(tau^2*(phi^2 - 1)^3*(phi - 1)^2) - (8*phi*sigma^2*(phi*tau - 4*phi^(tau/2)*(tau/2 + 1) + phi^tau*(tau + 1) + 3))/(tau^2*(phi^2 - 1)^2*(phi - 1)^2) + (16*phi*sigma^2*(3*phi - tau/2 - 4*phi^(tau/2 + 1) + (phi^2*tau)/2 + phi^(tau + 1)))/(tau^2*(phi^2 - 1)^2*(phi - 1)^3)

**Comment by Yuming-Zhang** [comment]
@coatless 
Hi James:
That was what I did in MATLAB. 

Eg: for the MA1 process:
`syms theta; syms tau; syms sigma
f=(1+theta^2)*(tau/2-(tau-3)*(theta/(1+theta^2)))*(sigma^2)/(tau^2/4)`

This yields:
`f =
 
(4*sigma^2*(theta^2 + 1)*(tau/2 - (theta*(tau - 3))/(theta^2 + 1)))/tau^2`

And I took multiple derivatives, it yields:
`>> diff(f,theta,2)
 
ans =
 
(8*sigma^2*(tau/2 - (theta*(tau - 3))/(theta^2 + 1)))/tau^2 - (16*sigma^2*theta*((tau - 3)/(theta^2 + 1) - (2*theta^2*(tau - 3))/(theta^2 + 1)^2))/tau^2 + (4*sigma^2*(theta^2 + 1)*((6*theta*(tau - 3))/(theta^2 + 1)^2 - (8*theta^3*(tau - 3))/(theta^2 + 1)^3))/tau^2`

`>> diff(f,theta,4)
 
ans =
 
(48*sigma^2*((6*theta*(tau - 3))/(theta^2 + 1)^2 - (8*theta^3*(tau - 3))/(theta^2 + 1)^3))/tau^2 - (4*sigma^2*(theta^2 + 1)*((120*theta*(tau - 3))/(theta^2 + 1)^3 - (480*theta^3*(tau - 3))/(theta^2 + 1)^4 + (384*theta^5*(tau - 3))/(theta^2 + 1)^5))/tau^2 + (32*sigma^2*theta*((6*(tau - 3))/(theta^2 + 1)^2 - (48*theta^2*(tau - 3))/(theta^2 + 1)^3 + (48*theta^4*(tau - 3))/(theta^2 + 1)^4))/tau^2`

So it is impossible to finally get answer 0 with derivatives. (I notice from other processes that we are expected to get 0 finally right?)

So I wonder whether there's anything wrong with my input? Or it is possible that we may not get 0 from the derivatives?

**Comment by coatless** [comment]
Within the other processes what happens is the first derivative takes out the variable. Thus, the term that is left is constant. Hence, when the second derivative occurs, we have 0 since the derivative of a constant is zero. We are not trying to solve for 0 in this case. We are merely trying to find what the analytical derivatives are.

**Comment by coatless** [comment]
Switch QN to:

 \[{X_t} = \sqrt {12{Q^2}} \left( {{U_t} - {U_{t - 1}}} \right)\]

**Comment by coatless** [comment]
Replace ARMA(p,q) with ARMA(1,1) with haar being:

\[\frac{{\left[ {\frac{\tau }{2}{{\left( {1 - {\phi _1}} \right)}^2}\left( {1 - {\phi _1}{\theta _1} + {\theta ^2}} \right) + \left( {{\phi _1} - {\theta _1}} \right)\left( {1 - {\phi _1}{\theta _1}} \right)\left( {\tau  - 3 - \tau \phi  + 4\phi _1^n - \phi _1^{2n}} \right)} \right]{\sigma ^2}}}{{\frac{{{\tau ^2}}}{4}{{\left( {1 - {\phi _1}} \right)}^2}\left( {1 - \phi _1^2} \right)}}\]

**Comment by Yuming-Zhang** [comment]
@coatless 
Changes in "modified wv_vignette":

1. Check only simple models in individual process and composite models in composite process.

2. Simplify QN formula and change all QN related composite models' formulas.

3. Random Walk process to WV formula has cancelled 2 (simplified)

4. Question: I re-install the gmwm R package with  `install.packages("gmwm")`, but the gts graphing object’s default values are still not "axis.x.label, axis.y.label to 'Time' and 'Observation'". It has merged right? So how can I update the latest gmwm package? I cannot use `install.packages("gmwm")` because it is still the one from CRAN right?

**Comment by Yuming-Zhang** [comment]
@coatless 

Changes in "All formulas are aligned":

1.All formulas are aligned now.

2. If would be great if you can double check the derivatives for AR1 and MA1

**Comment by coatless** [comment]
Awesome job on this @Yuming-Zhang .

We're going to not ship this vignette with the package as the overall size on this commit is **5 mb**! (More than the alotted size for packages on CRAN.)

I'll instead push it to the [smac-group.com/computing](http://smac-group.com/computing).

**Pull request closed without merging**
