### PR TITLE
Expanded imu options

### PR DESCRIPTION
**Pull request by Wenchao-Yang**
Modified imu associated functions to remove the restriction that gyroscope and accelerometer data must have same number of columns
#125

### CODE REVIEW

**Comment by Wenchao-Yang** [comment]
@coatless 
1. I have written test cases to make sure '[.imu' works, but I'm not 100% sure. Could you please go through this function after merging the pull request?

2. 
The following codes still don't work. Could you please help me fix it?
```
data(imu6)
test1 = imu(imu6, gyros = 1:3, accels = 4:6)
str(test1) #Error
```

**Comment by coatless** [comment]
For the `imu`, could we improve the axis labeling functionality.

e.g.
 
```
 sensor = imu(imu6, 
               gyros = 1:3,		               gyros = 1:3,
               accels = 4:6, 		               accels = 4:6, 
              axis = c('X','Y','Z'),		       axis = c('X','Y','Z','X','Y','Z'),
               freq = 100)		               freq = 100)
```

I'd like to retain the properties of the left. That is, if the number of gyros and accels are equal, then we just duplicate the axis via:

```r
rep(axis, each = 2)
```

See other inline comments.

**Comment by coatless** [comment]
Nice job Wenchao!

**Comment by coatless** [comment]
IMU Changes that allow for uneven data (#125)

Bug fixes:
#139 , #117, #118, #138

**Pull request merged**
